# Generated by Django 5.1.4 on 2025-03-31 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_cart_amount_cart_currency_cart_customer_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='razorpay_payment_id',
            new_name='razorpay_transaction_id',
        ),
    ]
