# Generated by Django 5.1.4 on 2025-03-31 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_razorpay_payment_id_cart_razorpay_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='razorpay_transaction_id',
            new_name='razorpay_payment_id',
        ),
    ]
