# Generated by Django 5.1.4 on 2025-03-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_colorvarient_sizevarient_product_color_varients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color_varients',
            field=models.ManyToManyField(blank=True, related_name='ColorVarient', to='products.colorvarient'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size_varients',
            field=models.ManyToManyField(blank=True, related_name='SizeVarient', to='products.sizevarient'),
        ),
    ]
