# Generated by Django 5.1.4 on 2025-03-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateField(default='2052-01-31'),
        ),
    ]
