# Generated by Django 5.1.4 on 2025-03-29 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_coupon_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='expiry_date',
        ),
    ]
